---
abstract: 'Tail calls for subroutines and methods'
author:
  - 'Yuval Kogman'
build_requires:
  B::Hooks::OP::Check::EntersubForCV: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::use::ok: 0
configure_requires:
  B::Hooks::OP::Check::EntersubForCV: 0
  ExtUtils::Depends: 0.302
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Call-Tail
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check::EntersubForCV: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nothingmuch/Sub-Call-Tail.git
version: 0.05
